# Generated by Django 5.1.7 on 2025-03-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='country',
            field=models.CharField(default='DE', max_length=2),
        ),
    ]
